### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by pandrei7** [pandrei7/fake-news-app#1]
This application uses a simple icon as a logo. It is stored in the `static/img/icon.jpg` file.

We would like to add a new logo, which would reflect the fact that the application tries to find fake news.

The new logo would be used as the favicon for the web application, but later it could be displayed on the front page and in the README.

There are not many restrictions related to file format, a simple PNG with a transparent background is ok. If you can provide a vector image, that would be a plus. :slightly_smiling_face:

**Comment by atharvabhoite7** [comment]
Hey! @pandrei7 ! I'm interested in this. Please can you assign it to me?

**Comment by pandrei7** [comment]
Hi! Sure, I'll assign it now.
